INSERT INTO comparisons (rule, field, type, text) VALUES (1, 'remarks', 'includes', 'Oranje spaarrekening');
INSERT INTO comparisons (rule, field, type, text) VALUES (2, 'remarks', 'includes', '3275357');
INSERT INTO comparisons (rule, field, type, text) VALUES (3, 'description', 'includes', 'Kosten OranjePakket');
INSERT INTO comparisons (rule, field, type, text) VALUES (4, 'remarks', 'includes', 's677385420201801128248');
INSERT INTO comparisons (rule, field, type, text) VALUES (5, 'account', 'equals', 'NL74INGB0654972370');
INSERT INTO comparisons (rule, field, type, text) VALUES (5, 'otheraccount', 'equals', 'NL62INGB0689027346');
INSERT INTO comparisons (rule, field, type, text) VALUES (6, 'otheraccount', 'equals', 'NL74INGB0654972370');
INSERT INTO comparisons (rule, field, type, text) VALUES (6, 'account', 'equals', 'NL62INGB0689027346');
INSERT INTO comparisons (rule, field, type, text) VALUES (7, 'account', 'equals', 'NL62INGB0689027346');
INSERT INTO comparisons (rule, field, type, text) VALUES (7, 'otheraccount', 'equals', 'NL92INGB0660741024');
INSERT INTO comparisons (rule, field, type, text) VALUES (8, 'remarks', 'includes', '210703775H0001');
INSERT INTO comparisons (rule, field, type, text) VALUES (9, 'description', 'includes', 'ASR VITALITEIT');
INSERT INTO comparisons (rule, field, type, text) VALUES (10, 'remarks', 'includes', '01DN0000000000000000000000000054899');
INSERT INTO comparisons (rule, field, type, text) VALUES (11, 'description', 'includes', 'Dierenbescherming');
INSERT INTO comparisons (rule, field, type, text) VALUES (12, 'remarks', 'includes', '1919213977P201806261112');
INSERT INTO comparisons (rule, field, type, text) VALUES (13, 'remarks', 'includes', 'R1670339');
INSERT INTO comparisons (rule, field, type, text) VALUES (14, 'remarks', 'includes', '90-MN-BL');
INSERT INTO comparisons (rule, field, type, text) VALUES (15, 'remarks', 'includes', '79-XSX-1');
INSERT INTO comparisons (rule, field, type, text) VALUES (16, 'description', 'includes', 'DEGIRO');
INSERT INTO comparisons (rule, field, type, text) VALUES (17, 'description', 'includes', 'Autobedrijf Ueffing');
INSERT INTO comparisons (rule, field, type, text) VALUES (18, 'description', 'includes', 'SPYSaigon Vietnamese Enschede');
INSERT INTO comparisons (rule, field, type, text) VALUES (19, 'description', 'includes', 'AHWallerbosch');
INSERT INTO comparisons (rule, field, type, text) VALUES (20, 'description', 'includes', 'COOP Boekelo');
INSERT INTO comparisons (rule, field, type, text) VALUES (21, 'description', 'includes', 'NEDAP NV');
INSERT INTO comparisons (rule, field, type, text) VALUES (22, 'description', 'includes', 'Hair by Paulien');
INSERT INTO comparisons (rule, field, type, text) VALUES (23, 'remarks', 'includes', 'Lidmaatschap ENIAC');
INSERT INTO comparisons (rule, field, type, text) VALUES (24, 'remarks', 'includes', '000100654972370');
INSERT INTO comparisons (rule, field, type, text) VALUES (25, 'description', 'includes', 'Dienst Uitvoering Onderwijs');
INSERT INTO comparisons (rule, field, type, text) VALUES (26, 'remarks', 'includes', 'MS-99-LD');
INSERT INTO comparisons (rule, field, type, text) VALUES (27, 'description', 'includes', 'ICS Card');
INSERT INTO comparisons (rule, field, type, text) VALUES (27, 'amount', 'equals', '-100,00');
INSERT INTO comparisons (rule, field, type, text) VALUES (28, 'otheraccount', 'INSERTincludes', 'NL33INGB0000039196');
INSERT INTO comparisons (rule, field, type, text) VALUES (29, 'remarks', 'includes', '282793593NL74INGB0654972370');
INSERT INTO comparisons (rule, field, type, text) VALUES (30, 'remarks', 'includes', '210703775H9002');
INSERT INTO comparisons (rule, field, type, text) VALUES (31, 'remarks', 'includes', '1080000249790');
INSERT INTO comparisons (rule, field, type, text) VALUES (32, 'remarks', 'includes', 'ALL0010971804.01');
INSERT INTO comparisons (rule, field, type, text) VALUES (33, 'description', 'includes', 'TLS BV inz. OV-Chipkaart');
INSERT INTO comparisons (rule, field, type, text) VALUES (34, 'description', 'includes', 'Powerpeers');
INSERT INTO comparisons (rule, field, type, text) VALUES (35, 'description', 'includes', 'ENERGIEDIRECT');
INSERT INTO comparisons (rule, field, type, text) VALUES (36, 'remarks', 'includes', '00BL40NX');
INSERT INTO comparisons (rule, field, type, text) VALUES (37, 'description', 'includes', 'ALBERT HEIJN');
INSERT INTO comparisons (rule, field, type, text) VALUES (38, 'description', 'includes', 'IKEA');
INSERT INTO comparisons (rule, field, type, text) VALUES (39, 'description', 'includes', 'NETFLIX');
INSERT INTO comparisons (rule, field, type, text) VALUES (40, 'remarks', 'includes', 'LA872201802270737029360002');
INSERT INTO comparisons (rule, field, type, text) VALUES (41, 'description', 'includes', 'Kosten tweede Betaalpas');
INSERT INTO comparisons (rule, field, type, text) VALUES (42, 'description', 'includes', 'Albert Heijn');
INSERT INTO comparisons (rule, field, type, text) VALUES (43, 'remarks', 'includes', '000001189395');
INSERT INTO comparisons (rule, field, type, text) VALUES (44, 'description', 'includes', 'LB Fil.');
INSERT INTO comparisons (rule, field, type, text) VALUES (45, 'description', 'includes', 'KWANTUM');
INSERT INTO comparisons (rule, field, type, text) VALUES (46, 'description', 'includes', 'ARGOS');
INSERT INTO comparisons (rule, field, type, text) VALUES (47, 'description', 'includes', 'SNACKBAR');
INSERT INTO comparisons (rule, field, type, text) VALUES (48, 'description', 'includes', 'PRAXIS');
INSERT INTO comparisons (rule, field, type, text) VALUES (49, 'description', 'includes', 'Leen Bakker');
INSERT INTO comparisons (rule, field, type, text) VALUES (50, 'description', 'includes', 'JYSK');
INSERT INTO comparisons (rule, field, type, text) VALUES (51, 'description', 'includes', 'Action');
INSERT INTO comparisons (rule, field, type, text) VALUES (52, 'description', 'includes', 'Blokker');
INSERT INTO comparisons (rule, field, type, text) VALUES (53, 'description', 'includes', 'Kruidvat');
INSERT INTO comparisons (rule, field, type, text) VALUES (54, 'description', 'includes', 'Xenos');
INSERT INTO comparisons (rule, field, type, text) VALUES (55, 'description', 'includes', 'HEMA');
INSERT INTO comparisons (rule, field, type, text) VALUES (56, 'description', 'includes', 'Kinepolis');
INSERT INTO comparisons (rule, field, type, text) VALUES (57, 'description', 'includes', 'DEKAMARKT');
INSERT INTO comparisons (rule, field, type, text) VALUES (58, 'remarks', 'includes', 'Spotify');
INSERT INTO comparisons (rule, field, type, text) VALUES (59, 'description', 'includes', 'Intratuin');
INSERT INTO comparisons (rule, field, type, text) VALUES (60, 'description', 'includes', 'HELLOFRESH');
INSERT INTO comparisons (rule, field, type, text) VALUES (61, 'description', 'includes', 'Takeaway.com');
INSERT INTO comparisons (rule, field, type, text) VALUES (62, 'remarks', 'includes', '000002453156');
INSERT INTO comparisons (rule, field, type, text) VALUES (63, 'description', 'includes', 'GBLT');
INSERT INTO comparisons (rule, field, type, text) VALUES (64, 'remarks', 'includes', 'Kinepolis');
INSERT INTO comparisons (rule, field, type, text) VALUES (65, 'description', 'includes', 'Gamma');
INSERT INTO comparisons (rule, field, type, text) VALUES (66, 'description', 'includes', 'GBTwente');
INSERT INTO comparisons (rule, field, type, text) VALUES (67, 'description', 'includes', 'MedikamenteDieGrenze');
INSERT INTO comparisons (rule, field, type, text) VALUES (68, 'description', 'includes', 'AH Kamphuis');
INSERT INTO comparisons (rule, field, type, text) VALUES (69, 'description', 'includes', 'Netto Tank');
INSERT INTO comparisons (rule, field, type, text) VALUES (70, 'description', 'includes', 'CAFETARIA');
INSERT INTO comparisons (rule, field, type, text) VALUES (71, 'remarks', 'includes', 'TK18114184A00');
INSERT INTO comparisons (rule, field, type, text) VALUES (72, 'description', 'includes', 'Lidl');
INSERT INTO comparisons (rule, field, type, text) VALUES (73, 'remarks', 'includes', 'Heracles');
INSERT INTO comparisons (rule, field, type, text) VALUES (74, 'description', 'includes', 'AH to go');
INSERT INTO comparisons (rule, field, type, text) VALUES (75, 'description', 'includes', 'Q PARK');
INSERT INTO comparisons (rule, field, type, text) VALUES (76, 'description', 'includes', 'Aldi');
INSERT INTO comparisons (rule, field, type, text) VALUES (77, 'description', 'includes', 'Total Weezebeek');
INSERT INTO comparisons (rule, field, type, text) VALUES (78, 'description', 'includes', 'BAUHAUS');
INSERT INTO comparisons (rule, field, type, text) VALUES (79, 'description', 'includes', 'Hornbach');
INSERT INTO comparisons (rule, field, type, text) VALUES (80, 'description', 'includes', 'Karwei');
INSERT INTO comparisons (rule, field, type, text) VALUES (81, 'description', 'includes', 'Kosten tweede rekeninghouder');
INSERT INTO comparisons (rule, field, type, text) VALUES (82, 'description', 'includes', 'Tango');
INSERT INTO comparisons (rule, field, type, text) VALUES (83, 'remarks', 'includes', '000040580144');
INSERT INTO comparisons (rule, field, type, text) VALUES (84, 'description', 'includes', 'D.G. Linde');
INSERT INTO comparisons (rule, field, type, text) VALUES (85, 'remarks', 'includes', '5163003');
INSERT INTO comparisons (rule, field, type, text) VALUES (86, 'description', 'includes', 'Albert Bezorgservice');
INSERT INTO comparisons (rule, field, type, text) VALUES (87, 'description', 'includes', 'TMC*P');
INSERT INTO comparisons (rule, field, type, text) VALUES (88, 'description', 'includes', 'McDonalds');
INSERT INTO comparisons (rule, field, type, text) VALUES (89, 'remarks', 'includes', '301084265');
INSERT INTO comparisons (rule, field, type, text) VALUES (90, 'description', 'includes', 'Decathlon');
INSERT INTO comparisons (rule, field, type, text) VALUES (91, 'description', 'includes', 'De Buren');
INSERT INTO comparisons (rule, field, type, text) VALUES (92, 'description', 'includes', 'Coop');
INSERT INTO comparisons (rule, field, type, text) VALUES (93, 'remarks', 'includes', '2001541991');
INSERT INTO comparisons (rule, field, type, text) VALUES (94, 'description', 'includes', 'Garmundo');
INSERT INTO comparisons (rule, field, type, text) VALUES (95, 'description', 'includes', 'BEAUTY EN WELLNESS');
INSERT INTO comparisons (rule, field, type, text) VALUES (96, 'remarks', 'includes', 'Bestelling bij Pizzeria Boekelo');
INSERT INTO comparisons (rule, field, type, text) VALUES (97, 'description', 'includes', 'Dierenarts');
INSERT INTO comparisons (rule, field, type, text) VALUES (98, 'description', 'includes', 'Vishandel');
INSERT INTO comparisons (rule, field, type, text) VALUES (99, 'description', 'includes', 'Snoepdog.nl');
INSERT INTO comparisons (rule, field, type, text) VALUES (100, 'description', 'includes', 'Butlon');
INSERT INTO comparisons (rule, field, type, text) VALUES (101, 'remarks', 'includes', 'Honderons');
INSERT INTO comparisons (rule, field, type, text) VALUES (102, 'description', 'includes', 'NV NEDAP');
INSERT INTO comparisons (rule, field, type, text) VALUES (103, 'description', 'includes', 'A.A. De Monnink');
INSERT INTO comparisons (rule, field, type, text) VALUES (104, 'remarks', 'includes', 'Stichting De Giro');