INSERT INTO categories (id, name) VALUES (4, 'Uitgaven');
INSERT INTO categories (id, name) VALUES (5, 'Wonen');
INSERT INTO categories (id, name) VALUES (6, 'Hypotheek');
INSERT INTO categories (id, name) VALUES (7, 'GWL');
INSERT INTO categories (id, name) VALUES (8, 'Belastingen');
INSERT INTO categories (id, name) VALUES (9, 'Gemeentelijk');
INSERT INTO categories (id, name) VALUES (10, 'Waterschap');
INSERT INTO categories (id, name) VALUES (11, 'Telecom');
INSERT INTO categories (id, name) VALUES (12, 'Televisie');
INSERT INTO categories (id, name) VALUES (13, 'Internet');
INSERT INTO categories (id, name) VALUES (14, 'Huishouden');
INSERT INTO categories (id, name) VALUES (15, 'Woonverzekering');
INSERT INTO categories (id, name) VALUES (16, 'Vervoer');
INSERT INTO categories (id, name) VALUES (17, 'Auto');
INSERT INTO categories (id, name) VALUES (18, 'Aanschaf');
INSERT INTO categories (id, name) VALUES (19, 'Verzekering');
INSERT INTO categories (id, name) VALUES (20, 'Wegenbelasting');
INSERT INTO categories (id, name) VALUES (21, 'Onderhoud');
INSERT INTO categories (id, name) VALUES (22, 'Motor');
INSERT INTO categories (id, name) VALUES (23, 'Aanschaf');
INSERT INTO categories (id, name) VALUES (24, 'Verzekering');
INSERT INTO categories (id, name) VALUES (25, 'Wegenbelasting');
INSERT INTO categories (id, name) VALUES (26, 'Onderhoud');
INSERT INTO categories (id, name) VALUES (27, 'Benzine');
INSERT INTO categories (id, name) VALUES (28, 'Vrije tijd');
INSERT INTO categories (id, name) VALUES (29, 'Hond');
INSERT INTO categories (id, name) VALUES (30, 'Voer');
INSERT INTO categories (id, name) VALUES (31, 'Snacks');
INSERT INTO categories (id, name) VALUES (32, 'Benodigdheden');
INSERT INTO categories (id, name) VALUES (33, 'Dierenarts');
INSERT INTO categories (id, name) VALUES (34, 'Overige uitgaven');
INSERT INTO categories (id, name) VALUES (35, 'Telefoon');
INSERT INTO categories (id, name) VALUES (36, 'Aanschaf');
INSERT INTO categories (id, name) VALUES (37, 'Abonnement');
INSERT INTO categories (id, name) VALUES (38, 'Medisch');
INSERT INTO categories (id, name) VALUES (39, 'Zorgverzekering');
INSERT INTO categories (id, name) VALUES (40, 'Tandarts');
INSERT INTO categories (id, name) VALUES (41, 'Fysiotherapie');
INSERT INTO categories (id, name) VALUES (42, 'Eigen bijdrage');
INSERT INTO categories (id, name) VALUES (43, 'Eigen risico');
INSERT INTO categories (id, name) VALUES (44, 'Anticonceptiepil');
INSERT INTO categories (id, name) VALUES (45, 'Sport');
INSERT INTO categories (id, name) VALUES (76, 'Cadeau''s');
INSERT INTO categories (id, name) VALUES (77, 'Persoonlijke verzorging');
INSERT INTO categories (id, name) VALUES (78, 'Kleding & schoenen');
INSERT INTO categories (id, name) VALUES (79, 'Kapper');
INSERT INTO categories (id, name) VALUES (80, 'Lidmaatschappen, abonnement & verzekeringen');
INSERT INTO categories (id, name) VALUES (81, 'Overlijdensverzekering');
INSERT INTO categories (id, name) VALUES (82, 'Boodschappen');
INSERT INTO categories (id, name) VALUES (83, 'Lunch');
INSERT INTO categories (id, name) VALUES (84, 'Bankkosten');
INSERT INTO categories (id, name) VALUES (85, 'a.s.r. Vitality');
INSERT INTO categories (id, name) VALUES (86, 'Goede doelen');
INSERT INTO categories (id, name) VALUES (87, 'Dierenbescherming');
INSERT INTO categories (id, name) VALUES (88, 'Studieschuld');
INSERT INTO categories (id, name) VALUES (89, 'Beleggen');
INSERT INTO categories (id, name) VALUES (90, 'Accessoires');
INSERT INTO categories (id, name) VALUES (91, 'Openbaar vervoer');
INSERT INTO categories (id, name) VALUES (92, 'Bril');
INSERT INTO categories (id, name) VALUES (93, 'Vakantie');
INSERT INTO categories (id, name) VALUES (94, 'Uitstapjes');
INSERT INTO categories (id, name) VALUES (95, 'Inrichting');
INSERT INTO categories (id, name) VALUES (96, 'Tuin');
INSERT INTO categories (id, name) VALUES (97, 'ENIAC');
INSERT INTO categories (id, name) VALUES (75, 'Hobby''s');
INSERT INTO categories (id, name) VALUES (46, 'KNMV');
INSERT INTO categories (id, name) VALUES (47, 'Verzorgingsproducten');
INSERT INTO categories (id, name) VALUES (48, 'Parkeren');
INSERT INTO categories (id, name) VALUES (491, 'ANWB');
INSERT INTO categories (id, name) VALUES (50, 'Boetes');
INSERT INTO categories (id, name) VALUES (51, 'Rijlessen');
INSERT INTO categories (id, name) VALUES (52, 'Zaalvoetbal');
INSERT INTO categories (id, name) VALUES (53, 'Afhalen/bezorgen');
INSERT INTO categories (id, name) VALUES (54, 'Accessoires');
INSERT INTO categories (id, name) VALUES (55, 'Reisverzekering');
INSERT INTO categories (id, name) VALUES (56, 'Klussen');
INSERT INTO categories (id, name) VALUES (57, 'Benodigdheden');
INSERT INTO categories (id, name) VALUES (58, 'Spotify');
INSERT INTO categories (id, name) VALUES (59, 'Training');
INSERT INTO categories (id, name) VALUES (60, 'Schoonmaakster');
INSERT INTO categories (id, name) VALUES (61, 'Inkomsten');
INSERT INTO categories (id, name) VALUES (62, 'Werk');
INSERT INTO categories (id, name) VALUES (63, 'Salaris');
INSERT INTO categories (id, name) VALUES (64, '13e maand');
INSERT INTO categories (id, name) VALUES (65, 'Hypotheekrenteaftrek');
INSERT INTO categories (id, name) VALUES (66, 'Belastingteruggave');
INSERT INTO categories (id, name) VALUES (67, 'Dividend');
INSERT INTO categories (id, name) VALUES (68, 'Verkopen');
INSERT INTO categories (id, name) VALUES (69, 'Overige');
INSERT INTO categories (id, name) VALUES (70, 'Overige');
INSERT INTO categories (id, name) VALUES (71, 'Spaarrekening');
INSERT INTO categories (id, name) VALUES (72, 'Ongecategoriseerd');
INSERT INTO categories (id, name) VALUES (73, 'Van/naar gezamenlijk');
INSERT INTO categories (id, name) VALUES (74, 'Lening');

UPDATE categories SET parent = 35 WHERE id = 90;
UPDATE categories SET parent = 4 WHERE id = 5;
UPDATE categories SET parent = 5 WHERE id = 6;
UPDATE categories SET parent = 5 WHERE id = 7;
UPDATE categories SET parent = 5 WHERE id = 8;
UPDATE categories SET parent = 8 WHERE id = 9;
UPDATE categories SET parent = 8 WHERE id = 10;
UPDATE categories SET parent = 5 WHERE id = 11;
UPDATE categories SET parent = 11 WHERE id = 12;
UPDATE categories SET parent = 11 WHERE id = 13;
UPDATE categories SET parent = 5 WHERE id = 14;
UPDATE categories SET parent = 5 WHERE id = 15;
UPDATE categories SET parent = 4 WHERE id = 16;
UPDATE categories SET parent = 16 WHERE id = 17;
UPDATE categories SET parent = 17 WHERE id = 18;
UPDATE categories SET parent = 17 WHERE id = 19;
UPDATE categories SET parent = 17 WHERE id = 20;
UPDATE categories SET parent = 17 WHERE id = 21;
UPDATE categories SET parent = 16 WHERE id = 22;
UPDATE categories SET parent = 22 WHERE id = 23;
UPDATE categories SET parent = 22 WHERE id = 24;
UPDATE categories SET parent = 22 WHERE id = 25;
UPDATE categories SET parent = 22 WHERE id = 26;
UPDATE categories SET parent = 16 WHERE id = 27;
UPDATE categories SET parent = 4 WHERE id = 28;
UPDATE categories SET parent = 4 WHERE id = 29;
UPDATE categories SET parent = 29 WHERE id = 30;
UPDATE categories SET parent = 29 WHERE id = 31;
UPDATE categories SET parent = 29 WHERE id = 32;
UPDATE categories SET parent = 29 WHERE id = 33;
UPDATE categories SET parent = 4 WHERE id = 34;
UPDATE categories SET parent = 11 WHERE id = 35;
UPDATE categories SET parent = 35 WHERE id = 36;
UPDATE categories SET parent = 35 WHERE id = 37;
UPDATE categories SET parent = 4 WHERE id = 38;
UPDATE categories SET parent = 38 WHERE id = 39;
UPDATE categories SET parent = 38 WHERE id = 40;
UPDATE categories SET parent = 38 WHERE id = 41;
UPDATE categories SET parent = 38 WHERE id = 42;
UPDATE categories SET parent = 38 WHERE id = 43;
UPDATE categories SET parent = 42 WHERE id = 44;
UPDATE categories SET parent = 28 WHERE id = 45;
UPDATE categories SET parent = 28 WHERE id = 76;
UPDATE categories SET parent = 4 WHERE id = 77;
UPDATE categories SET parent = 77 WHERE id = 78;
UPDATE categories SET parent = 77 WHERE id = 79;
UPDATE categories SET parent = 4 WHERE id = 80;
UPDATE categories SET parent = 80 WHERE id = 81;
UPDATE categories SET parent = 14 WHERE id = 82;
UPDATE categories SET parent = 82 WHERE id = 83;
UPDATE categories SET parent = 34 WHERE id = 84;
UPDATE categories SET parent = 80 WHERE id = 85;
UPDATE categories SET parent = 34 WHERE id = 86;
UPDATE categories SET parent = 86 WHERE id = 87;
UPDATE categories SET parent = 34 WHERE id = 88;
UPDATE categories SET parent = 34 WHERE id = 89;
UPDATE categories SET parent = 22 WHERE id = 54;
UPDATE categories SET parent = 16 WHERE id = 91;
UPDATE categories SET parent = 38 WHERE id = 92;
UPDATE categories SET parent = 28 WHERE id = 93;
UPDATE categories SET parent = 28 WHERE id = 94;
UPDATE categories SET parent = 5 WHERE id = 95;
UPDATE categories SET parent = 5 WHERE id = 96;
UPDATE categories SET parent = 80 WHERE id = 97;
UPDATE categories SET parent = 28 WHERE id = 75;
UPDATE categories SET parent = 80 WHERE id = 46;
UPDATE categories SET parent = 77 WHERE id = 47;
UPDATE categories SET parent = 16 WHERE id = 48;
UPDATE categories SET parent = 80 WHERE id = 49;
UPDATE categories SET parent = 16 WHERE id = 50;
UPDATE categories SET parent = 16 WHERE id = 51;
UPDATE categories SET parent = 94 WHERE id = 52;
UPDATE categories SET parent = 82 WHERE id = 53;
UPDATE categories SET parent = 35 WHERE id = 58;
UPDATE categories SET parent = 80 WHERE id = 55;
UPDATE categories SET parent = 5 WHERE id = 56;
UPDATE categories SET parent = 14 WHERE id = 57;
UPDATE categories SET parent = 11 WHERE id = 58;
UPDATE categories SET parent = 29 WHERE id = 59;
UPDATE categories SET parent = 14 WHERE id = 60;
UPDATE categories SET parent = 61 WHERE id = 62;
UPDATE categories SET parent = 62 WHERE id = 63;
UPDATE categories SET parent = 62 WHERE id = 64;
UPDATE categories SET parent = 61 WHERE id = 65;
UPDATE categories SET parent = 61 WHERE id = 66;
UPDATE categories SET parent = 61 WHERE id = 67;
UPDATE categories SET parent = 61 WHERE id = 68;
UPDATE categories SET parent = 61 WHERE id = 69;
UPDATE categories SET parent = 70 WHERE id = 71;
UPDATE categories SET parent = 70 WHERE id = 72;
UPDATE categories SET parent = 70 WHERE id = 73;
UPDATE categories SET parent = 70 WHERE id = 74;