INSERT INTO rules (name, category) VALUES ('Spaarrekening', 71);
INSERT INTO rules (name, category) VALUES ('Motorverzekering', 24);
INSERT INTO rules (name, category) VALUES ('Bankkosten', 84);
INSERT INTO rules (name, category) VALUES ('Abonnement telefoon', 37);
INSERT INTO rules (name, category) VALUES ('Van Tanja naar gezamenlijk', 73);
INSERT INTO rules (name, category) VALUES ('Van gezamenlijk naar Tanja', 73);
INSERT INTO rules (name, category) VALUES ('Van Matt naar gezamenlijk', 73);
INSERT INTO rules (name, category) VALUES ('Hypotheekrenteaftrek', 65);
INSERT INTO rules (name, category) VALUES ('a.s.r. Vitality', 85);
INSERT INTO rules (name, category) VALUES ('Autoverzekering', 19);
INSERT INTO rules (name, category) VALUES ('De Dierenbescherming', 87);
INSERT INTO rules (name, category) VALUES ('Uitvaartverzekering', 81);
INSERT INTO rules (name, category) VALUES ('Studieschuld', 88);
INSERT INTO rules (name, category) VALUES ('Motorwegenbelasting', 25);
INSERT INTO rules (name, category) VALUES ('Autowegenbelasting', 20);
INSERT INTO rules (name, category) VALUES ('Beleggen', 89);
INSERT INTO rules (name, category) VALUES ('Benzine', 27);
INSERT INTO rules (name, category) VALUES ('Lunch (loempias)', 83);
INSERT INTO rules (name, category) VALUES ('Lunch (AH Groenlo)', 83);
INSERT INTO rules (name, category) VALUES ('Boodschappen (Coop Boekelo)', 82);
INSERT INTO rules (name, category) VALUES ('Werk', 62);
INSERT INTO rules (name, category) VALUES ('Kapper', 79);
INSERT INTO rules (name, category) VALUES ('Lidmaatschap ENIAC', 97);
INSERT INTO rules (name, category) VALUES ('Motorverzekering', 24);
INSERT INTO rules (name, category) VALUES ('Dienst Uitvoering Onderwijs', 88);
INSERT INTO rules (name, category) VALUES ('Motorwegenbelasting (oud)', 25);
INSERT INTO rules (name, category) VALUES ('Benzine', 27);
INSERT INTO rules (name, category) VALUES ('KNMV Lidmaatschap', 46);
INSERT INTO rules (name, category) VALUES ('ANWB Lidmaatschap', 49);
INSERT INTO rules (name, category) VALUES ('Hypotheekrenteaftrek', 65);
INSERT INTO rules (name, category) VALUES ('Zorgverzekering (oud)', 39);
INSERT INTO rules (name, category) VALUES ('Autoverzekering (oud)', 19);
INSERT INTO rules (name, category) VALUES ('OV-chipkaart', 91);
INSERT INTO rules (name, category) VALUES ('GWL (Powerpeers)', 7);
INSERT INTO rules (name, category) VALUES ('GWL (Energiedirect)', 7);
INSERT INTO rules (name, category) VALUES ('Hypotheek', 6);
INSERT INTO rules (name, category) VALUES ('Boodschappen (AH)', 82);
INSERT INTO rules (name, category) VALUES ('Inrichting (IKEA)', 95);
INSERT INTO rules (name, category) VALUES ('Netflix', 12);
INSERT INTO rules (name, category) VALUES ('Reisverzekering (SNS)', 55);
INSERT INTO rules (name, category) VALUES ('Bankkosten', 84);
INSERT INTO rules (name, category) VALUES ('Boodschappen (AH)', 82);
INSERT INTO rules (name, category) VALUES ('Woonverzekering (Centraal Beheer)', 15);
INSERT INTO rules (name, category) VALUES ('Leen Bakker (Inrichting)', 95);
INSERT INTO rules (name, category) VALUES ('Kwantum (Inrichting)', 95);
INSERT INTO rules (name, category) VALUES ('Benzine', 27);
INSERT INTO rules (name, category) VALUES ('Snackbar', 53);
INSERT INTO rules (name, category) VALUES ('Praxis (Klussen)', 56);
INSERT INTO rules (name, category) VALUES ('Leen Bakker', 95);
INSERT INTO rules (name, category) VALUES ('Jysk', 95);
INSERT INTO rules (name, category) VALUES ('Action', 57);
INSERT INTO rules (name, category) VALUES ('Blokker', 57);
INSERT INTO rules (name, category) VALUES ('Kruidvat', 57);
INSERT INTO rules (name, category) VALUES ('Xenos', 95);
INSERT INTO rules (name, category) VALUES ('Hema', 57);
INSERT INTO rules (name, category) VALUES ('Bioscoop', 94);
INSERT INTO rules (name, category) VALUES ('Dekamarkt', 82);
INSERT INTO rules (name, category) VALUES ('Spotify', 58);
INSERT INTO rules (name, category) VALUES ('Intratuin', 96);
INSERT INTO rules (name, category) VALUES ('HelloFresh', 82);
INSERT INTO rules (name, category) VALUES ('Thuisbezorgd', 53);
INSERT INTO rules (name, category) VALUES ('Vitens', 7);
INSERT INTO rules (name, category) VALUES ('GBLT', 10);
INSERT INTO rules (name, category) VALUES ('Kinepolis', 94);
INSERT INTO rules (name, category) VALUES ('Gamma', 56);
INSERT INTO rules (name, category) VALUES ('GBTwente', 9);
INSERT INTO rules (name, category) VALUES ('Die Grenze', 57);
INSERT INTO rules (name, category) VALUES ('AH Haaksbergen', 82);
INSERT INTO rules (name, category) VALUES ('Netto Tank', 27);
INSERT INTO rules (name, category) VALUES ('Cafetaria', 53);
INSERT INTO rules (name, category) VALUES ('Tweak', 12);
INSERT INTO rules (name, category) VALUES ('Lidl (Boodschappen)', 82);
INSERT INTO rules (name, category) VALUES ('Heracles', 75);
INSERT INTO rules (name, category) VALUES ('AH to go', 82);
INSERT INTO rules (name, category) VALUES ('Q PARK (Parkeren)', 48);
INSERT INTO rules (name, category) VALUES ('Aldi', 82);
INSERT INTO rules (name, category) VALUES ('Total Weezebeek', 27);
INSERT INTO rules (name, category) VALUES ('Bauhaus', 56);
INSERT INTO rules (name, category) VALUES ('Hornbach', 56);
INSERT INTO rules (name, category) VALUES ('Karwei', 56);
INSERT INTO rules (name, category) VALUES ('Bankkosten', 84);
INSERT INTO rules (name, category) VALUES ('Tango', 27);
INSERT INTO rules (name, category) VALUES ('FBTO Woonverzekering', 15);
INSERT INTO rules (name, category) VALUES ('Broodjes zondag', 82);
INSERT INTO rules (name, category) VALUES ('GWL (Oxxio)', 7);
INSERT INTO rules (name, category) VALUES ('Boodschappen bezorgen', 82);
INSERT INTO rules (name, category) VALUES ('Parkeren', 48);
INSERT INTO rules (name, category) VALUES ('McDonalds', 53);
INSERT INTO rules (name, category) VALUES ('Woonverzekering (Centraal Beheer)', 15);
INSERT INTO rules (name, category) VALUES ('Decathlon', 78);
INSERT INTO rules (name, category) VALUES ('De Buren', 94);
INSERT INTO rules (name, category) VALUES ('Coop', 82);
INSERT INTO rules (name, category) VALUES ('Vitens', 7);
INSERT INTO rules (name, category) VALUES ('Garmundo', 96);
INSERT INTO rules (name, category) VALUES ('Bad Boekelo', 94);
INSERT INTO rules (name, category) VALUES ('Pizzeria Boekelo', 53);
INSERT INTO rules (name, category) VALUES ('Dierenarts', 33);
INSERT INTO rules (name, category) VALUES ('Vis', 83);
INSERT INTO rules (name, category) VALUES ('Snoepdog', 31);
INSERT INTO rules (name, category) VALUES ('Butlon', 53);
INSERT INTO rules (name, category) VALUES ('Honderons', 59);
INSERT INTO rules (name, category) VALUES ('Salaris + onkostenvergoedingen', 62);
INSERT INTO rules (name, category) VALUES ('Schoonmaakster', 60);
INSERT INTO rules (name, category) VALUES ('Stichting De Giro', 89);